language: python

sudo: false
python:
  - 2.7
  - 3.5

install:
  # - pip install -r requirements.txt
  - pip install pyflakes pytest pytest-cov coveralls

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - pyflakes .
  # - py.test
  - py.test --cov=module tests/

after_success:
  - coveralls
